---
version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle:/usr/local/bundle
      - .:/var/apps/web
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true

  redis:
    image: redis

  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  bundle:
    driver: local
  db:
    driver: local
